use_rerun: true

simulation:
  control_frequency: 200.0
  simulation_frequency: 1000.0
  log_frequency: 20.0
  duration: 70.0 # in seconds

quadrotor:
  mass: 1.3
  gravity: 9.81
  drag_coefficient: 0.000
  inertia_matrix: [3.04e-3, 0.0, 0.0, 0.0, 4.55e-3, 0.0, 0.0, 0.0, 2.82e-3]

controller:
  pos_gains:
    kp: [7.1, 7.1, 11.9]
    kd: [2.4, 2.4, 6.7]
    ki: [0.0, 0.0, 0.0]
  att_gains:
    kp: [1.5, 1.5, 1.0]
    kd: [0.13, 0.13, 0.1]
    ki: [0.0, 0.0, 0.0]
  pos_max_int: [10.0, 10.0, 10.0]
  att_max_int: [0.5, 0.5, 0.5]

imu:
  accel_noise_std: 0.02
  gyro_noise_std: 0.01
  bias_instability: 0.0001

maze:
  lower_bounds: [-3.0, -2.0, 0.0]
  upper_bounds: [3.0, 2.0, 2.0]
  num_obstacles: 20

camera:
  resolution: [128, 96]
  fov: 90.0
  near: 0.1
  far: 5.0

mesh:
  division: 7
  spacing: 0.5

planner_schedule:
  - step: 1000
    planner_type: MinimumJerkLine
    params:
      end_position: [0.0, 0.0, 1.0]
      end_yaw: 0.0
      duration: 2.5
  - step: 5000
    planner_type: Lissajous
    params:
      center: [0.5, 0.5, 1.0]
      amplitude: [0.5, 0.5, 0.2]
      frequency: [1.0, 2.0, 3.0]
      phase: [0.0, 1.5707963267948966, 0.0] # [0.0, PI/2, 0.0]
      duration: 20.0
      end_yaw: 6.283185307179586 # 2*PI
      ramp_time: 5.0
  - step: 27000
    planner_type: Circle
    params:
      center: [0.5, 0.5, 1.0]
      radius: 0.5
      angular_velocity: 1.0
      duration: 5.0
      ramp_time: 2.0
  - step: 32000
    planner_type: MinimumJerkLine
    params:
      end_position: [-2.5, 0.0, 1.0]
      end_yaw: 0.0
      duration: 3.0
  - step: 35000
    planner_type: ObstacleAvoidance
    params:
      target_position: [2.5, 1.0, 0.5]
      duration: 10.0
      end_yaw: 0.0
      k_att: 0.03
      k_rep: 0.01
      k_vortex: 0.005
      d0: 0.5
      d_target: 0.5
      max_speed: 0.1
  - step: 45000
    planner_type: MinimumSnapWaypoint
    params:
      waypoints:
        - [1.0, 1.0, 1.5]
        - [-1.0, 1.0, 1.75]
        - [0.0, -1.0, 1.0]
        - [0.0, 0.0, 0.5]
      yaws: [1.5707963267948966, 3.141592653589793, -1.5707963267948966, 0.0] # [PI/2, PI, -PI/2, 0.0]
      segment_times: [5.0, 5.0, 5.0, 5.0]
  - step: 65000
    planner_type: Landing
    params:
      duration: 5.0
